### ISSUE TITLE
Can't run the local server for the docs - contributing

### ISSUE THREAD

**Issue by rhanb** [sarcadass/granim.js#41]
Hi,

I followed the contribution guideline, everything works fine except the local server for the docs. 
I want to make a PR for a new feature proposal  that could be useful for many users but can't implement the docs.

`npm start`

```
> granim@1.1.1 start /Users/rhanb/Documents/DevLove/OSS/JS/granim.js
> cd docs/ && node server.js

/Users/rhanb/Documents/DevLove/OSS/JS/granim.js/docs/server.js:34
server.connection({ port: httpPort });
       ^

TypeError: server.connection is not a function
    at Object.<anonymous> (/Users/rhanb/Documents/DevLove/OSS/JS/granim.js/docs/server.js:34:8)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
```

Best regards

**Comment by sarcadass** [comment]
Hello @rhanb,
I fixed the server issue, by updating to the latest Hapi version and I updated the server config to the latest API version. It should work fine now.

**Comment by rhanb** [comment]
Parfait merci @sarcadass
